using System.Collections.Generic;
using static DNT.DNT;
using static DNT.DNT.Element;
using static Terraria.ID.NPCID;

namespace DNT
{
    public partial class DNTNPCs
    {
        public static readonly Dictionary<int, Element> ContactDamageTypes = new()
        {
            #region Corruption
            { EaterofSouls, Piercing },
            { DevourerHead, Piercing },
            { DevourerBody, Bludgeoning },
            { DevourerTail, Bludgeoning },
            { DarkMummy, Bludgeoning | Necrotic },
            { DesertGhoulCorruption, Bludgeoning | Necrotic },
            { Slimer, Acid },
            { Slimer2, Acid },
            { CorruptSlime, Acid },
            { CursedHammer, Bludgeoning },
            { Corruptor, Piercing },
            { VileSpit, Acid },
            { SeekerHead, Piercing },
            { SeekerBody, Bludgeoning },
            { SeekerTail, Bludgeoning },
            { Clinger, Piercing },
            { PigronCorruption, Piercing },
            { BigMimicCorruption, Piercing | Acid },
            { SandsharkCorrupt, Piercing },
            #endregion
            #region Crimson
            { Crimera, Piercing },
            { Herpling, Acid },
            { CrimsonAxe, Slashing },
            { PigronCrimson, Piercing },
            { FaceMonster, Piercing },
            { FloatyGross, Necrotic },
            { Crimslime, Acid },
            { BloodCrawler, Piercing | Poison },
            { BloodCrawlerWall, Piercing | Poison },
            { BloodFeeder, Piercing },
            { BloodJelly, Poison },
            { IchorSticker, Piercing },
            { BigMimicCrimson, Piercing | Acid },
            { DesertGhoulCrimson, Bludgeoning | Necrotic },
            { SandsharkCrimson, Piercing },
            { BloodMummy, Bludgeoning | Necrotic },
            #endregion
            #region Hallow
            { Pixie, Slashing },
            { LightMummy, Bludgeoning | Necrotic },
            { DesertGhoulHallow, Bludgeoning | Necrotic },
            { EnchantedSword, Slashing },
            { Unicorn, Bludgeoning },
            { ChaosElemental, Bludgeoning },
            { Gastropod, Acid },
            { IlluminantBat, Piercing },
            { IlluminantSlime, Acid },
            { PigronHallow, Piercing },
            { RainbowSlime, Acid | Radiant },
            { BigMimicHallow, Piercing | Acid },
            { SandsharkHallow, Piercing },
            #endregion
            #region Underground
            #region Skeleton
            { Skeleton, Bludgeoning },
            { BoneThrowingSkeleton, Bludgeoning },
            { BoneThrowingSkeleton2, Bludgeoning },
            { BoneThrowingSkeleton3, Bludgeoning },
            { BoneThrowingSkeleton4, Bludgeoning },
            { UndeadMiner, Piercing },
            { Tim, Bludgeoning },
            { ChaosBallTim, Fire },
            { SkeletonArcher, Piercing },
            { ArmoredSkeleton, Bludgeoning },
            { HeadacheSkeleton, Bludgeoning },
            { MisassembledSkeleton, Bludgeoning },
            { PantlessSkeleton, Bludgeoning },
            #endregion
            { GiantWormHead, Piercing },
            { GiantWormBody, Bludgeoning },
            { GiantWormTail, Bludgeoning },
            { MotherSlime, Acid },
            { CaveBat, Piercing },
            { BlueJellyfish, Poison },
            { Mimic, Piercing | Acid },
            { GiantBat, Piercing },
            { DiggerHead, Piercing },
            { DiggerBody, Bludgeoning },
            { DiggerTail, Bludgeoning },
            { AnglerFish, Piercing },
            { GreenJellyfish, Poison },
            { ToxicSludge, Acid | Poison },
            { BlackRecluse, Piercing | Poison },
            { WallCreeper, Piercing | Poison },
            { WallCreeperWall, Piercing | Poison },
            { RuneWizard, Piercing },
            { LostGirl, Bludgeoning },
            { Nymph, Slashing },
            { CochinealBeetle, Slashing },
            { CyanBeetle, Slashing },
            { LacBeetle, Slashing },
            { Crawdad, Bludgeoning },
            { Crawdad2, Bludgeoning },
            { GiantShelly, Bludgeoning },
            { GiantShelly2, Bludgeoning },
            { Salamander, Acid },
            { Salamander2, Acid },
            { Salamander3, Acid },
            { Salamander4, Acid },
            { Salamander5, Acid },
            { Salamander6, Acid },
            { Salamander7, Acid },
            { Salamander8, Acid },
            { Salamander9, Acid },
            { RockGolem, Bludgeoning },

            { Medusa, Slashing },
            { GreekSkeleton, Piercing },
            { GraniteGolem, Bludgeoning },
            { GraniteFlyer, Bludgeoning },
            #endregion
            #region Glowing Mushroom
            { FungoFish, Poison | Psychic },
            { AnomuraFungus, Piercing | Psychic },
            { MushiLadybug, Psychic },
            { FungiBulb, Bludgeoning | Psychic },
            { GiantFungiBulb, Bludgeoning | Psychic },
            { FungiSpore, Bludgeoning | Psychic },
            { SporeBat, Piercing | Psychic },
            { SporeSkeleton, Bludgeoning | Psychic },
            #endregion
            #region Snow/Ice
            { IceSlime, Acid | Cold },
            { SpikedIceSlime, Cold | Piercing },
            { IceBat, Cold | Piercing },
            { Wolf, Piercing },
            { UndeadViking, Slashing },
            { IceElemental, Cold },
            { SnowFlinx, Bludgeoning },
            { ArmoredViking, Slashing },
            { IcyMerman, Bludgeoning | Cold },
            { IceGolem, Bludgeoning | Cold },
            { IceMimic, Piercing | Cold },
            #endregion
            #region Ocean
            { PinkJellyfish, Poison },
            { Shark, Piercing },
            { Crab, Bludgeoning },
            { SeaSnail, Acid },
            { Squid, Piercing },
            #endregion
            #region Dungeon
            { AngryBones, Bludgeoning },
            { AngryBonesBig, Bludgeoning },
            { AngryBonesBigMuscle, Bludgeoning },
            { AngryBonesBigHelmet, Bludgeoning },
            { DarkCaster, Bludgeoning },
            { WaterSphere, Cold },
            { CursedSkull, Necrotic },
            { SpikeBall, Bludgeoning | Piercing },
            { DungeonSlime, Acid | Piercing },
            { BlazingWheel, Fire },

            { RustyArmoredBonesAxe, Slashing | Poison },
            { RustyArmoredBonesFlail, Bludgeoning | Poison },
            { RustyArmoredBonesSword, Slashing | Poison },
            { RustyArmoredBonesSwordNoArmor, Slashing | Poison },
            { BlueArmoredBones, Bludgeoning },
            { BlueArmoredBonesMace, Bludgeoning },
            { BlueArmoredBonesNoPants, Bludgeoning },
            { BlueArmoredBonesSword, Slashing },
            { HellArmoredBones, Slashing | Fire },
            { HellArmoredBonesSword, Slashing | Fire },
            { HellArmoredBonesMace, Bludgeoning | Fire },
            { HellArmoredBonesSpikeShield, Piercing | Fire },
            { RaggedCaster, Bludgeoning },
            { RaggedCasterOpenCoat, Bludgeoning },
            { Necromancer, Bludgeoning },
            { NecromancerArmored, Bludgeoning },
            { DiabolistRed, Bludgeoning },
            { DiabolistWhite, Bludgeoning },
            { BoneLee, Force },
            { DungeonSpirit, Necrotic },
            { GiantCursedSkull, Necrotic },
            { Paladin, Bludgeoning | Radiant },
            { SkeletonSniper, Piercing },
            { TacticalSkeleton, Piercing },
            { SkeletonCommando, Piercing },
            { CultistArcherBlue, Piercing },
            { CultistArcherWhite, Piercing },
            #endregion
            #region Desert
            { Vulture, Piercing },
            { Antlion, Piercing },
            { WalkingAntlion, Piercing },
            { FlyingAntlion, Piercing },
            { LarvaeAntlion, Piercing },
            { GiantWalkingAntlion, Piercing },
            { GiantFlyingAntlion, Piercing },
            { TombCrawlerHead, Piercing },
            { TombCrawlerBody, Bludgeoning },
            { TombCrawlerTail, Bludgeoning },
            { SandSlime, Bludgeoning },
            { Tumbleweed, Bludgeoning },

            { DuneSplicerHead, Piercing },
            { DuneSplicerBody, Bludgeoning },
            { DuneSplicerTail, Bludgeoning },
            { Mummy, Bludgeoning | Necrotic },
            { DesertGhoul, Bludgeoning | Necrotic },
            { DesertLamiaLight, Slashing },
            { DesertScorpionWalk, Bludgeoning },
            { DesertScorpionWall, Bludgeoning },
            { DesertBeast, Piercing },
            { SandElemental, Bludgeoning },
            { SandShark, Piercing },

            { DesertLamiaDark, Slashing },
            { DesertDjinn, Bludgeoning },
            #endregion
            #region Jungle
            { Hornet, Piercing | Poison },
            { HornetFatty, Piercing | Poison },
            { HornetHoney, Piercing | Poison },
            { HornetLeafy, Piercing | Poison },
            { HornetSpikey, Piercing | Poison },
            { HornetStingy, Piercing | Poison },
            { ManEater, Piercing },
            { JungleBat, Piercing },
            { DoctorBones, Bludgeoning },
            { Snatcher, Piercing },
            { Piranha, Piercing },
            { GiantFlyingFox, Piercing },
            { GiantTortoise, Bludgeoning },
            { Arapaima, Piercing },
            { AngryTrapper, Piercing },
            { MossHornet, Piercing | Poison },
            { Derpling, Piercing },
            { Lihzahrd, Slashing },
            { LihzahrdCrawler, Slashing },
            { SpikedJungleSlime, Piercing | Poison },
            { Moth, Psychic },
            { Bee, Piercing | Poison },
            { BeeSmall, Piercing | Poison },
            { JungleCreeper, Piercing | Poison },
            { JungleCreeperWall, Piercing | Poison },
            { FlyingSnake, Piercing },
            { BigMimicJungle, Piercing | Acid },
            #endregion
            #region Hell
            { LavaSlime, Fire },
            { Hellbat, Fire | Piercing },
            { FireImp, Fire },
            { BurningSphere, Fire },
            { BoneSerpentHead, Piercing },
            { BoneSerpentBody, Bludgeoning },
            { BoneSerpentTail, Bludgeoning },
            { Demon, Slashing },
            { VoodooDemon, Slashing },
            { Lavabat, Fire | Piercing },
            { RedDevil, Piercing },
            { DemonTaxCollector, Slashing },
            #endregion

            #region Misc
            #region Zombie
            { Zombie, Bludgeoning },
            { MaggotZombie, Bludgeoning },
            { TorchZombie, Bludgeoning },
            { ArmedZombie, Bludgeoning },
            { ArmedTorchZombie, Bludgeoning },
            { ArmedZombieEskimo, Bludgeoning },
            { ArmedZombiePincussion, Bludgeoning },
            { ArmedZombieSwamp, Bludgeoning },
            { ArmedZombieTwiggy, Bludgeoning },
            { ArmedZombieCenx, Bludgeoning },
            { BaldZombie, Bludgeoning },
            { ZombieEskimo, Bludgeoning | Cold },
            { PincushionZombie, Bludgeoning },
            { SlimedZombie, Bludgeoning },
            { SwampZombie, Bludgeoning },
            { TwiggyZombie, Bludgeoning },
            { FemaleZombie, Bludgeoning },
            { ZombieRaincoat, Bludgeoning },
            { ZombieMushroom, Bludgeoning | Psychic },
            { ZombieMushroomHat, Bludgeoning | Psychic },
            { ZombieDoctor, Bludgeoning },
            { ZombieSuperman, Bludgeoning },
            { ZombiePixie, Bludgeoning },
            { ZombieXmas, Bludgeoning },
            { ZombieSweater, Bludgeoning },
            { SkeletonTopHat, Bludgeoning },
            { SkeletonAstonaut, Bludgeoning },
            { SkeletonAlien, Bludgeoning },
            #endregion
            #region DemonEye
            { DemonEye, Bludgeoning },
            { CataractEye, Bludgeoning },
            { SleepyEye, Bludgeoning },
            { DialatedEye, Bludgeoning },
            { GreenEye, Bludgeoning },
            { PurpleEye, Bludgeoning },
            { DemonEyeOwl, Bludgeoning },
            { DemonEyeSpaceship, Bludgeoning },
            #endregion
            #region Slime
            { BlueSlime, Acid },
            { SlimeSpiked, Acid },
            { UmbrellaSlime, Acid },
            { SlimeMasked, Acid },
            { HoppinJack, Acid },
            { SlimeRibbonGreen, Acid },
            { SlimeRibbonRed, Acid },
            { SlimeRibbonWhite, Acid },
            { SlimeRibbonYellow, Acid },
            { GoldenSlime, Acid },
            { ShimmerSlime, Acid },
            #endregion

            { Gnome, Bludgeoning },
            { Dandelion, Bludgeoning },
            { FlyingFish, Bludgeoning },
            { Raven, Piercing },
            { Ghost, Necrotic },
            { MeteorHead, Bludgeoning | Fire },
            { Harpy, Slashing },

            { Wraith, Necrotic },
            { WanderingEye, Bludgeoning },
            { PossessedArmor, Bludgeoning },
            { AngryNimbus, Thunder },
            { WyvernHead, Piercing },
            { WyvernLegs, Slashing },
            { WyvernBody, Bludgeoning },
            { WyvernBody2, Bludgeoning },
            { WyvernBody3, Bludgeoning },
            { WyvernTail, Slashing },
            #endregion

            #region Events
            #region Blood Moon
            { CorruptBunny, Piercing },
            { CrimsonBunny, Piercing },
            { CorruptGoldfish, Piercing },
            { CrimsonGoldfish, Piercing },
            { CorruptPenguin, Piercing },
            { CrimsonPenguin, Piercing },
            { BloodZombie, Bludgeoning },
            { Drippler, Bludgeoning },
            { TheGroom, Bludgeoning },
            { TheBride, Bludgeoning },
            { ZombieMerman, Bludgeoning },
            { EyeballFlyingFish, Bludgeoning },

            { Clown, Bludgeoning },
            { ChatteringTeethBomb, Piercing },
            { BloodNautilus, Bludgeoning },
            { BloodSquid, Piercing },
            { GoblinShark, Piercing },
            { BloodEelHead, Piercing },
            { BloodEelBody, Bludgeoning },
            { BloodEelTail, Bludgeoning },
            #endregion
            #region Goblin Army
            { GoblinPeon, Bludgeoning },
            { GoblinWarrior, Slashing },
            { GoblinSorcerer, Bludgeoning },
            { ChaosBall, Fire },
            { GoblinScout, Piercing },
            { GoblinArcher, Piercing },
            { GoblinSummoner, Piercing },
            { ShadowFlameApparition, Fire | Necrotic },
            #endregion
            #region Old One's Army
            { DD2Betsy, Piercing },
            { DD2GoblinT1, Slashing },
            { DD2GoblinT2, Slashing },
            { DD2GoblinT3, Slashing },
            { DD2GoblinBomberT1, Bludgeoning },
            { DD2GoblinBomberT2, Bludgeoning },
            { DD2GoblinBomberT3, Bludgeoning },
            { DD2WyvernT1, Piercing },
            { DD2WyvernT2, Piercing },
            { DD2WyvernT3, Piercing },
            { DD2JavelinstT1, Piercing },
            { DD2JavelinstT2, Piercing },
            { DD2JavelinstT3, Piercing },
            { DD2DarkMageT1, Psychic },
            { DD2DarkMageT3, Psychic },
            { DD2SkeletonT1, Bludgeoning },
            { DD2SkeletonT3, Bludgeoning },
            { DD2WitherBeastT2, Piercing },
            { DD2WitherBeastT3, Piercing },
            { DD2DrakinT2, Piercing },
            { DD2DrakinT3, Piercing },
            { DD2KoboldWalkerT2, Bludgeoning },
            { DD2KoboldWalkerT3, Bludgeoning },
            { DD2KoboldFlyerT2, Force },
            { DD2KoboldFlyerT3, Force },
            { DD2OgreT2, Bludgeoning },
            { DD2OgreT3, Bludgeoning },
            { DD2LightningBugT3, Piercing },
            #endregion
            #region Frost Legion
            { SnowmanGangsta, Cold },
            { MisterStabby, Piercing },
            { SnowBalla, Cold },
            #endregion
            #region Pirate Invasion
            { PirateDeckhand, Piercing },
            { PirateCorsair, Slashing },
            { PirateDeadeye, Bludgeoning },
            { PirateCrossbower, Bludgeoning },
            { PirateCaptain, Slashing },
            { Parrot, Piercing },
            { PirateShip, Bludgeoning },
            { PirateShipCannon, Bludgeoning },
            { PirateGhost, Necrotic },
            #endregion
            #region Pumpkin Moon
            { Scarecrow1, Bludgeoning },
            { Scarecrow2, Bludgeoning },
            { Scarecrow3, Bludgeoning },
            { Scarecrow4, Bludgeoning },
            { Scarecrow5, Bludgeoning },
            { Scarecrow6, Bludgeoning },
            { Scarecrow7, Bludgeoning },
            { Scarecrow8, Bludgeoning },
            { Scarecrow9, Bludgeoning },
            { Scarecrow10, Bludgeoning },
            { HeadlessHorseman, Slashing },
            { MourningWood, Bludgeoning },
            { Splinterling, Bludgeoning },
            { Pumpking, Piercing },
            { PumpkingBlade, Slashing },
            { Hellhound, Piercing },
            { Poltergeist, Necrotic },
            #endregion
            #region Frost Moon
            { ZombieElf, Bludgeoning },
            { ZombieElfBeard, Bludgeoning },
            { ZombieElfGirl, Bludgeoning },
            { PresentMimic, Piercing },
            { GingerbreadMan, Bludgeoning },
            { Yeti, Bludgeoning },
            { Everscream, Bludgeoning },
            { IceQueen, Cold | Slashing },
            { SantaNK1, Bludgeoning },
            { ElfCopter, Bludgeoning },
            { Nutcracker, Bludgeoning },
            { NutcrackerSpinning, Bludgeoning },
            { ElfArcher, Piercing },
            { Krampus, Bludgeoning },
            { Flocko, Cold | Slashing },
            #endregion
            #region Eclipse
            { Reaper, Necrotic | Slashing },
            { VampireBat, Piercing },
            { Vampire, Piercing },
            { Frankenstein, Bludgeoning },
            { SwampThing, Bludgeoning | Poison },
            { Eyezor, Bludgeoning },
            { Butcher, Slashing },
            { CreatureFromTheDeep, Bludgeoning },
            { Fritz, Bludgeoning },
            { Nailhead, Piercing },
            { Psycho, Slashing },
            { DeadlySphere, Piercing },
            { DrManFly, Acid },
            { ThePossessed, Piercing },
            { Mothron, Piercing },
            { MothronSpawn, Piercing },
            #endregion
            #region Martian Madness
            { BrainScrambler, Bludgeoning },
            { RayGunner, Bludgeoning },
            { MartianOfficer, Bludgeoning },
            { GrayGrunt, Bludgeoning },
            { MartianEngineer, Bludgeoning },
            { MartianTurret, Bludgeoning },
            { MartianDrone, Force },
            { GigaZapper, Lightning | Piercing },
            { ScutlixRider, Lightning | Piercing },
            { Scutlix, Piercing },
            { MartianSaucer, Bludgeoning },
            { MartianSaucerTurret, Bludgeoning },
            { MartianSaucerCannon, Bludgeoning },
            { MartianSaucerCore, Bludgeoning },
            { MartianProbe, Bludgeoning },
            { MartianWalker, Bludgeoning },
            #endregion
            #region Pillars
            { LunarTowerStardust, Poison },
            { StardustWormHead, Piercing | Poison },
            { StardustWormBody, Bludgeoning },
            { StardustWormTail, Bludgeoning },
            { StardustCellBig, Bludgeoning | Poison },
            { StardustCellSmall, Bludgeoning | Poison },
            { StardustJellyfishBig, Piercing | Poison },
            { StardustSpiderBig, Piercing | Poison },
            { StardustSpiderSmall, Piercing | Poison },
            { StardustSoldier, Bludgeoning | Poison },

            { LunarTowerSolar, Fire },
            { SolarCrawltipedeHead, Piercing | Fire },
            { SolarCrawltipedeBody, Bludgeoning | Fire },
            { SolarCrawltipedeTail, Bludgeoning | Fire },
            { SolarDrakomire, Piercing | Fire },
            { SolarDrakomireRider, Piercing | Fire },
            { SolarSpearman, Piercing | Fire },
            { SolarSroller, Bludgeoning | Fire },
            { SolarCorite, Bludgeoning | Fire },
            { SolarSolenian, Slashing | Fire },
            { SolarFlare, Fire },
            { SolarGoop, Fire },

            { LunarTowerNebula, Psychic },
            { NebulaBrain, Bludgeoning | Psychic },
            { NebulaHeadcrab, Force | Psychic },
            { NebulaBeast, Piercing | Psychic },
            { NebulaSoldier, Bludgeoning | Psychic },

            { LunarTowerVortex, Lightning },
            { VortexRifleman, Piercing },
            { VortexHornetQueen, Piercing },
            { VortexHornet, Piercing },
            { VortexLarva, Piercing },
            { VortexSoldier, Bludgeoning },
            #endregion
            #endregion

            #region Bosses
            { KingSlime, Acid},
            { EyeofCthulhu, Bludgeoning  },
            { ServantofCthulhu, Bludgeoning  },
            { EaterofWorldsHead, Piercing },
            { EaterofWorldsBody, Bludgeoning },
            { EaterofWorldsTail, Bludgeoning },
            { BrainofCthulhu, Bludgeoning },
            { Creeper, Bludgeoning },
            { VileSpitEaterOfWorlds, Acid },
            { QueenBee, Piercing },
            { SkeletronHead, Bludgeoning },
            { SkeletronHand, Bludgeoning },
            { DungeonGuardian, Bludgeoning },
            { Deerclops, Slashing },
            { WallofFlesh, Piercing },
            { WallofFleshEye, Bludgeoning },
            { TheHungry, Bludgeoning },
            { TheHungryII, Bludgeoning },
            { LeechHead, Piercing },
            { LeechBody, Bludgeoning },
            { LeechTail, Bludgeoning },

            { QueenSlimeBoss, Acid },
            { QueenSlimeMinionBlue, Acid | Piercing },
            { QueenSlimeMinionPink, Acid },
            { QueenSlimeMinionPurple, Acid },
            { Retinazer, Bludgeoning },
            { Spazmatism, Bludgeoning },
            { SkeletronPrime, Bludgeoning },
            { PrimeCannon, Bludgeoning },
            { PrimeLaser, Bludgeoning },
            { PrimeSaw, Slashing },
            { PrimeVice, Bludgeoning },
            { TheDestroyer, Piercing },
            { TheDestroyerBody, Bludgeoning },
            { TheDestroyerTail, Bludgeoning },
            { Probe, Bludgeoning },
            { Plantera, Bludgeoning },
            { PlanterasHook, Slashing },
            { PlanterasTentacle, Piercing },
            { Spore, Poison },
            { Golem, Bludgeoning },
            { GolemFistLeft, Bludgeoning },
            { GolemFistRight, Bludgeoning },
            { GolemHead, Bludgeoning },
            { GolemHeadFree, Bludgeoning },
            { DukeFishron, Piercing },
            { DetonatingBubble, Cold | Force },
            { Sharkron, Piercing },
            { Sharkron2, Piercing },
            { CultistBoss, Piercing },
            { CultistBossClone, Psychic },
            { CultistDragonHead, Piercing },
            { CultistDragonBody1, Bludgeoning },
            { CultistDragonBody2, Bludgeoning },
            { CultistDragonBody3, Bludgeoning },
            { CultistDragonBody4, Bludgeoning },
            { CultistDragonTail, Bludgeoning },
            { AncientCultistSquidhead, Psychic },
            { AncientLight, Force },
            { AncientDoom, Psychic },
            { MoonLordHand, Piercing },
            { MoonLordHead, Piercing },
            { MoonLordFreeEye, Bludgeoning },
            #endregion
        };
    }
}
