using System.Collections.Generic;
using Terraria;
using Terraria.DataStructures;
using Terraria.ModLoader;
using static DNT.DNT;
using static DNT.DNT.Element;
using static Terraria.ID.ProjectileID;

namespace DNT
{
    public class DNTProjectiles : GlobalProjectile
    {
        public static readonly Dictionary<int, Element> DefaultDamageTypes = new()
        {
            #region Equip
            { Bee, Piercing | Poison },
            { GiantBee, Piercing | Poison },
            { StarCloakStar, Radiant },
            { StarVeilStar, Radiant },
            { InsanityShadowFriendly, Psychic },
            { VolatileGelatinBall, Radiant },
            { SporeTrap, Poison },
            { SporeTrap2, Poison },
            { SporeGas, Poison },
            { SporeGas2, Poison },
            { SporeGas3, Poison },

            { FlowerPetal, Piercing },
            { TitaniumStormShard, Piercing },
            { CrystalLeafShot, Piercing },
            { SpectreWrath, Necrotic },
            { StardustGuardian, Piercing },
            { StardustGuardianExplosion, Piercing },

            { MinecartMechLaser, Lightning },
            { ScutlixLaserFriendly, Lightning },
            { SantankMountRocket, Force },
            #endregion

            #region Magic
            #region PreHM
            { WandOfSparkingSpark, Fire },
            { WandOfFrostingFrost, Cold },
            { ThunderStaffShot, Lightning },
            { AmethystBolt, Force },
            { TopazBolt, Force },
            { SapphireBolt, Force },
            { EmeraldBolt, Force },
            { RubyBolt, Force },
            { DiamondBolt, Force },
            { AmberBolt, Force },
            { VilethornBase, Piercing },
            { VilethornTip, Piercing },
            { WeatherPainShot, Thunder },
            { MagicMissile, Force },
            { WaterStream, Cold },
            { BallofFire, Fire },
            { Flamelash, Fire },

            { ZapinatorLaser, Lightning },

            { WaterBolt, Cold },
            { BookOfSkullsSkull, Necrotic },
            { DemonScythe, Necrotic },

            { BloodCloudRaining, Psychic },
            { BloodRain, Psychic },
            #endregion
            #region HM
            { SkyFracture, Thunder },
            { CrystalPulse, Psychic },
            { CrystalPulse2, Psychic },
            { BallofFrost, Cold },
            { FrostBoltStaff, Cold },
            { CrystalVileShardHead, Piercing },
            { CrystalVileShardShaft, Piercing },
            { SoulDrain, Necrotic },
            { Meteor1, Bludgeoning | Fire },
            { Meteor2, Bludgeoning | Fire },
            { Meteor3, Bludgeoning | Fire },
            { PoisonFang, Poison },
            { RainbowRodBullet, Psychic },
            { UnholyTridentFriendly, Force },
            { BookStaffShot, Thunder },
            { DD2ApprenticeStorm, Thunder },
            { VenomFang, Poison },
            { NettleBurstEnd, Piercing },
            { NettleBurstLeft, Piercing },
            { NettleBurstRight, Piercing },
            { Bat, Piercing },
            { Blizzard, Cold },
            { InfernoFriendlyBlast, Fire },
            { InfernoFriendlyBolt, Fire },
            { ShadowBeamFriendly, Necrotic },
            { LostSoulFriendly, Necrotic },
            { PrincessWeapon, Radiant },
            { PineNeedleFriendly, Piercing },
            { BoulderStaffOfEarth, Bludgeoning },
            { ApprenticeStaffT3Shot, Fire },

            { PurpleLaser, Lightning },
            { Wasp, Piercing | Poison },
            { Leaf, Piercing },
            { RainbowBack, Radiant },
            { RainbowFront, Radiant },
            { HeatRay, Fire },
            { LaserMachinegun, Lightning },
            { ChargedBlasterCannon, Lightning },
            { Bubble, Cold },

            { CursedFlameFriendly, Fire | Necrotic },
            { GoldenShowerFriendly, Psychic },
            { CrystalStorm, Piercing },
            { MagnetSphereBall, Lightning | Thunder },
            { MagnetSphereBolt, Lightning | Thunder },
            { Typhoon, Cold | Slashing },
            { LunarFlare, Radiant },

            { IceBlock, Cold },
            { ClingerStaff, Fire | Necrotic },
            { RainFriendly, Cold },
            { MagicDagger, Force },
            { MedusaHead, Force },
            { SpiritFlame, Fire | Necrotic },
            { ShadowFlame, Fire | Necrotic },
            { SharpTears, Psychic },
            { EighthNote, Thunder },
            { QuarterNote, Thunder },
            { TiedEighthNote, Thunder },
            { ToxicFlask, Acid },
            { FairyQueenMagicItemShot, Radiant },
            { SparkleGuitar, Radiant | Thunder },
            { NebulaArcanum, Psychic },
            { NebulaArcanumSubshot, Psychic },
            { NebulaArcanumExplosionShot, Psychic },
            { NebulaArcanumExplosionShotShard, Psychic },
            { NebulaBlaze1, Psychic },
            { NebulaBlaze2, Psychic },
            { LastPrismLaser, Radiant },
            #endregion
            #endregion

            #region Melee
            #region PreHM Weapons
            { WoodenBoomerang, Bludgeoning },
            #region Metal
            { LightsBane, Slashing },
            { BallOHurt, Bludgeoning },
            { CorruptYoyo, Bludgeoning },

            { BloodButcherer, Slashing },
            { TheMeatball, Bludgeoning },
            { TheRottedFork, Piercing },
            { CrimsonYoyo, Bludgeoning },

            { Volcano, Fire },
            { BladeOfGrass, Poison },
            { Muramasa, Necrotic },
            { NightsEdge, Necrotic },
            #endregion
            { RulerStab, Bludgeoning },
            { GladiusStab, Piercing },
            { IceBolt, Cold },
            { TentacleSpike, Piercing },
            { Starfury, Thunder },
            { EnchantedBeam, Force },

            { Rally, Bludgeoning },
            { Code1, Bludgeoning },
            { Valor, Bludgeoning },
            { Cascade, Fire },
            { HiveFive, Poison },

            { Spear, Piercing },
            { Trident, Piercing },
            { ThunderSpear, Lightning },
            { Swordfish, Piercing },
            { DarkLance, Necrotic },

            { EnchantedBoomerang, Force },
            { FruitcakeChakram, Piercing },
            { BloodyMachete, Slashing },
            { Shroomerang, Psychic },
            { IceBoomerang, Cold },
            { ThornChakram, Poison },
            { CombatWrench, Bludgeoning },
            { Flamarang, Fire },
            { Trimarang, Force },

            { Mace, Bludgeoning },
            { FlamingMace, Fire },
            { BlueMoon, Cold },
            { Sunfury, Fire },
            { ChainKnife, Piercing },

            { Terragrim, Force },
            #endregion

            #region HM Weapons
            #region Metal
            { CobaltDrill, Piercing },
            { CobaltChainsaw, Slashing },
            { CobaltNaginata, Piercing },

            { PalladiumDrill, Piercing },
            { PalladiumChainsaw, Slashing },
            { PalladiumPike, Piercing },

            { MythrilDrill, Piercing },
            { MythrilChainsaw, Slashing },
            { MythrilHalberd, Piercing },

            { OrichalcumDrill, Piercing },
            { OrichalcumChainsaw, Slashing },
            { OrichalcumHalberd, Piercing },

            { AdamantiteDrill, Piercing },
            { AdamantiteChainsaw, Slashing },
            { AdamantiteGlaive, Piercing },

            { TitaniumDrill, Piercing },
            { TitaniumChainsaw, Slashing },
            { TitaniumTrident, Piercing },

            { Excalibur, Piercing  },
            { Gungnir, Radiant },
            { Hamdrax, Radiant },
            { LightDisc, Radiant },

            { SporeCloud, Poison },
            { ChlorophyteOrb, Poison },
            { ChlorophytePartisan, Poison },
            { ChlorophyteDrill, Poison },
            { ChlorophyteChainsaw, Poison },
            { ChlorophyteJackhammer, Poison },

            { TrueExcalibur, Radiant },
            { TrueNightsEdge, Necrotic },
            { TerraBlade2, Force },
            { TerraBlade2Shot, Force },
            #endregion
            { IceSickle, Cold },
            { FrostBoltSword, Cold },
            { SwordBeam, Radiant },
            { IchorSplash, Slashing },
            { Waffle, Fire },
            { DeathSickle, Necrotic },
            { TheHorsemansBlade, Fire },
            { FlamingJack, Fire },
            { OrnamentFriendly, Piercing },
            { OrnamentStar, Piercing },
            { SeedlerNut, Poison },
            { SeedlerThorn, Poison },
            { DD2SquireSonicBoom, Fire },
            { InfluxWaver, Lightning },
            { StarWrath, Thunder },
            { Meowmere, Thunder }, // Because it's noisy as FUCK

            { FormatC, Bludgeoning },
            { Gradient, Bludgeoning },
            { Chik, Radiant },
            { HelFire, Fire },
            { Amarok, Cold },
            { Code2, Bludgeoning },
            { Yelets, Poison },
            { RedsYoyo, Force },
            { ValkyrieYoyo, Lightning },
            { Kraken, Cold },
            { TheEyeOfCthulhu, Bludgeoning },
            { Terrarian, Force },

            { MonkStaffT2, Fire },
            { MonkStaffT2Ghast, Fire },
            { MushroomSpear, Psychic },
            { ObsidianSwordfish, Piercing },
            { NorthPoleSnowflake, Cold },
            { NorthPoleSpear, Cold },
            { NorthPoleWeapon, Cold },

            { FlyingKnife, Psychic },
            { BouncingShield, Bludgeoning },
            { Bananarang, Bludgeoning },
            { PossessedHatchet, Slashing },
            { PaladinsHammerFriendly, Radiant },

            { DripplerFlail, Bludgeoning },
            { DripplerFlailExtraBall, Bludgeoning },
            { TheDaoofPow, Necrotic | Radiant },
            { FlowerPow, Poison },
            { Anchor, Bludgeoning | Piercing },
            { ChainGuillotine, Piercing },
            { BoxingGlove, Bludgeoning },
            { GolemFist, Fire },
            { Flairon, Cold },

            { Arkhalis, Force },
            { JoustingLance, Piercing },
            { ShadowFlameKnife, Fire | Necrotic },
            { MonkStaffT1, Bludgeoning },
            { MonkStaffT1Explosion, Bludgeoning },
            { EatersBite, Necrotic },
            { TinyEater, Necrotic },
            { VampireKnife, Necrotic },
            { ShadowJoustingLance, Necrotic },
            { PiercingStarlight, Radiant },
            { MonkStaffT3, Lightning },
            { MonkStaffT3_AltShot, Lightning },
            { Daybreak, Fire },
            { DaybreakExplosion, Fire },
            { SolarWhipSword, Fire },
            { SolarWhipSwordExplosion, Fire },
            { FinalFractal, Force },
            { FirstFractal, Force },
            #endregion
            #endregion

            #region Ranged
            #region PreHM
            { BloodArrow, Psychic },
            { BeeArrow, Piercing | Poison },
            { Hellwing, Fire },

            { PewMaticHornShot, Bludgeoning },

            { Bullet, Piercing },
            { MeteorShot, Fire },
            { SilverBullet, Piercing },
            { PartyBullet, Piercing },

            { WoodenArrowFriendly, Piercing },
            { FlamingArrow, Piercing },
            { UnholyArrow, Piercing },
            { JestersArrow, Piercing },
            { HellfireArrow, Piercing },
            { FrostburnArrow, Piercing },
            { BoneArrowFromMerchant, Piercing },
            { ShimmerArrow, Piercing },

            { Seed, Bludgeoning },
            { PoisonDartBlowgun, Poison },

            { PaperAirplaneA, Bludgeoning },
            { PaperAirplaneB, Bludgeoning },
            { Shuriken, Piercing },
            { ThrowingKnife, Piercing },
            { PoisonedKnife, Poison },
            { SnowBallFriendly, Cold },
            { SpikyBall, Piercing },
            { Bone, Bludgeoning },
            { RottenEgg, Poison },
            { StarAnise, Piercing },
            { MolotovCocktail, Fire },
            { MolotovFire, Fire },
            { MolotovFire2, Fire },
            { MolotovFire3, Fire },
            { FrostDaggerfish, Cold },
            { JavelinFriendly, Piercing },
            { BoneJavelin, Piercing },
            { BoneDagger, Piercing },

            { Grenade, Force },
            { StickyGrenade, Force },
            { BouncyGrenade, Force },
            { Beenade, Piercing | Poison },
            { PartyGirlGrenade, Force },

            { SandBallGun, Bludgeoning },
            { CrimsandBallGun, Bludgeoning },
            { EbonsandBallGun, Bludgeoning },
            { PearlSandBallGun, Bludgeoning },
            { PainterPaintball, Bludgeoning },
            { Ale, Bludgeoning },
            { Harpoon, Bludgeoning },
            { StarCannonStar, Bludgeoning },
            #endregion
            #region HM
            { FrostArrow, Cold },
            { ShadowFlameArrow, Fire },
            { BoneArrow, Piercing },
            { DD2PhoenixBowShot, Fire },
            { PulseBolt, Force },
            { Stake, Piercing },
            { DD2BetsyArrow, Fire },
            { FairyQueenRangedItemShot, Radiant },
            { PhantasmArrow, Radiant },

            { BlackBolt, Force },
            { CandyCorn, Poison },
            { VortexBeaterRocket, Radiant },

            { NailFriendly, Piercing },
            { Stynger, Force },
            { StyngerShrapnel, Force },
            { JackOLantern, Fire },
            { Electrosphere, Lightning },
            { ElectrosphereMissile, Lightning },

            { ToxicBubble, Poison },
            { CopperCoin, Bludgeoning },
            { SilverCoin, Bludgeoning },
            { GoldCoin, Bludgeoning },
            { PlatinumCoin, Bludgeoning },
            { Flames, Fire },
            { MechanicalPiranha, Piercing },
            { SuperStar, Radiant },
            { SuperStarSlash, Radiant },

            { HolyArrow, Radiant },
            { HallowStar, Radiant },
            { CursedArrow, Fire },
            { IchorArrow, Psychic },
            { VenomArrow, Poison },
            { MoonlordArrow, Radiant },
            { MoonlordArrowTrail, Radiant },

            { CrystalBullet, Piercing },
            { CrystalShard, Piercing },
            { CursedBullet, Fire },
            { ChlorophyteBullet, Poison },
            { BulletHighVelocity, Piercing },
            { IchorBullet, Psychic },
            { NanoBullet, Lightning },
            { ExplosiveBullet, Force },
            { GoldenBullet, Piercing },
            { MoonlordBullet, Radiant },

            { CrystalDart, Piercing },
            { CursedDart, Fire },
            { IchorDart, Psychic },

            { RocketI, Force },
            { RocketII, Force },
            { RocketIII, Force },
            { RocketIV, Force },
            { GrenadeI, Force },
            { GrenadeII, Force },
            { GrenadeIII, Force },
            { GrenadeIV, Force },
            { ProximityMineI, Force },
            { ProximityMineII, Force },
            { ProximityMineIII, Force },
            { ProximityMineIV, Force },
            { ClusterRocketI, Force },
            { ClusterRocketII, Force },
            { ClusterMineI, Force },
            { ClusterMineII, Force },
            { ClusterFragmentsI, Piercing },
            { ClusterFragmentsII, Piercing },
            { DryRocket, Force },
            { WetRocket, Cold },
            { LavaRocket, Fire },
            { HoneyRocket, Cold },
            { DryGrenade, Force },
            { WetGrenade, Cold },
            { LavaGrenade, Fire },
            { HoneyGrenade, Cold },
            { DryMine, Force },
            { WetMine, Cold },
            { LavaMine, Fire },
            { HoneyMine, Cold },
            { MiniNukeRocketI, Force },
            { MiniNukeRocketII, Force },
            { MiniNukeGrenadeI, Force },
            { MiniNukeGrenadeII, Force },
            { MiniNukeMineI, Force },
            { MiniNukeMineII, Force },

            { RocketFireworkBlue, Force | Thunder },
            { RocketFireworkGreen, Force | Thunder },
            { RocketFireworkRed, Force | Thunder },
            { RocketFireworkYellow, Force | Thunder },
            { Celeb2Rocket, Force | Thunder },
            { Celeb2RocketExplosive, Force | Thunder },
            { Celeb2RocketExplosiveLarge, Force | Thunder },
            { Celeb2RocketLarge, Force | Thunder },
            { DrySnowmanRocket, Force | Cold },
            { WetSnowmanRocket, Cold },
            { LavaSnowmanRocket, Fire },
            { HoneySnowmanRocket, Cold },
            { RocketSnowmanI, Force | Cold },
            { RocketSnowmanII, Force | Cold },
            { RocketSnowmanIII, Force | Cold },
            { RocketSnowmanIV, Force | Cold },
            { ClusterSnowmanRocketI, Force | Cold },
            { ClusterSnowmanRocketII, Force | Cold },
            { ClusterSnowmanFragmentsI, Force | Cold },
            { ClusterSnowmanFragmentsII, Force | Cold },
            { MiniNukeSnowmanRocketI, Force | Cold },
            { MiniNukeSnowmanRocketII, Force | Cold },
            #endregion
            #endregion
            
            #region Summon
            #region PreHM
            { BabyBird, Piercing },
            { BabySlime, Acid },
            { FlinxMinion, Bludgeoning },
            { AbigailMinion, Necrotic },
            { HornetStinger, Poison },
            { VampireFrog, Acid },
            { ImpFireball, Fire },

            { HoundiusShootiusFireball, Fire },
            { DD2LightningAuraT1, Lightning },
            { DD2FlameBurstTowerT1Shot, Fire },
            { DD2ExplosiveTrapT1Explosion, Force },
            { DD2BallistraProj, Piercing },

            { BlandWhip, Slashing },
            { ThornWhip, Slashing },
            { BoneWhip, Slashing },
            #endregion
            #region HM
            { Smolstar, Psychic },
            { DangerousSpider, Poison },
            { JumperSpider, Poison },
            { VenomSpider, Poison },
            { PirateCaptain, Slashing },
            { OneEyedPirate, Slashing },
            { SoulscourgePirate, Slashing },
            { BatOfLight, Psychic },
            { Spazmamini, Piercing },
            { MiniRetinaLaser, Piercing },
            { DeadlySphere, Piercing },
            { PygmySpear, Piercing },
            { Raven, Piercing },
            { WhiteTigerPounce, Lightning },
            { StormTigerAttack, Lightning },
            { StormTigerTier1, Lightning },
            { StormTigerTier2, Lightning },
            { StormTigerTier3, Lightning },
            { MiniSharkron, Cold },
            { EmpressBlade, Radiant },
            { UFOLaser, Lightning },
            { StardustCellMinionShot, Poison },
            { StardustDragon1, Cold },
            { StardustDragon2, Cold },
            { StardustDragon3, Cold },
            { StardustDragon4, Cold },

            { SpiderEgg, Poison },
            { FrostBlastFriendly, Cold },
            { MoonlordTurretLaser, Radiant },
            { RainbowCrystalExplosion, Radiant },
            { DD2LightningAuraT2, Lightning },
            { DD2LightningAuraT3, Lightning },
            { DD2FlameBurstTowerT2Shot, Fire },
            { DD2FlameBurstTowerT3Shot, Fire },
            { DD2ExplosiveTrapT2Explosion, Force },
            { DD2ExplosiveTrapT3Explosion, Force },

            { FireWhip, Fire },
            { FireWhipProj, Fire },
            { CoolWhip, Cold },
            { CoolWhipProj, Cold },
            { SwordWhip, Radiant },
            { ScytheWhip, Necrotic },
            { ScytheWhipProj, Necrotic },
            { MaceWhip, Bludgeoning },
            { RainbowWhip, Radiant },
            #endregion
            #endregion

            #region Hostile
            #region PreHM
            { HarpyFeather, Piercing },
            { DemonSickle, Necrotic },
            { Stinger, Piercing | Poison },
            { WoodenArrowHostile, Piercing },
            { FireArrow, Fire },
            { IceSpike, Cold },
            { JungleSpike, Poison },
            { Skull, Necrotic },
            { SkeletonBone, Bludgeoning },
            { SpikedSlimeSpike, Acid },
            { DD2JavelinHostile, Piercing },
            { DD2DarkMageBolt, Psychic },
            { QueenBeeStinger, Piercing | Poison },
            { RollingCactus, Piercing },
            { RollingCactusSpike, Piercing },
            { DandelionSeed, Bludgeoning },
            { TorchGod, Fire },
            { DeerclopsIceSpike, Cold },
            { DeerclopsRangedProjectile, Cold },
            { InsanityShadowHostile, Psychic },
            #endregion
            #region HM
            { HappyBomb, Force },
            { EyeLaser, Lightning },
            { PinkLaser, Lightning },
            { CursedFlameHostile, Fire },
            { DeathLaser, Lightning },
            { EyeFire, Fire },
            { BombSkeletronPrime, Force },
            { SnowBallHostile, Cold },
            { BulletSnowman, Piercing },
            { UnholyTridentHostile, Necrotic },
            { FrostBlastHostile, Cold },
            { RuneBlast, Force },
            { CannonballHostile, Bludgeoning },
            { Fireball, Fire },
            { EyeBeam, Force },
            { RainNimbus, Cold },
            { SeedPlantera, Piercing },
            { PoisonSeedPlantera, Poison },
            { ThornBall, Piercing },
            { GoldenShowerHostile, Psychic },
            { ShadowBeamHostile, Necrotic },
            { InfernoHostileBlast, Fire },
            { InfernoHostileBolt, Fire },
            { LostSoulHostile, Necrotic },
            { Shadowflames, Fire },
            { PaladinsHammerHostile, Radiant },
            { SniperBullet, Piercing },
            { RocketSkeleton, Force },
            { FlamingWood, Fire },
            { GreekFire1, Fire },
            { GreekFire2, Fire },
            { FlamingScythe, Fire },
            { PineNeedleHostile, Piercing },
            { OrnamentHostile, Piercing },
            { OrnamentHostileShrapnel, Piercing },
            { FrostWave, Cold },
            { FrostShard, Cold },
            { Missile, Force },
            { Present, Bludgeoning },
            { Spike, Piercing },
            { Sharknado, Cold },
            { Cthulunado, Cold },
            { MartianTurretBolt, Lightning },
            { BrainScramblerBolt, Lightning },
            { GigaZapperSpear, Lightning },
            { SaucerDeathray, Lightning },
            { SaucerMissile, Lightning },
            { SaucerLaser, Lightning },
            { SaucerScrap, Lightning },
            { PhantasmalEye, Radiant },
            { PhantasmalSphere, Radiant },
            { PhantasmalDeathray, Radiant },
            { PhantasmalBolt, Radiant },
            { CultistBossIceMist, Cold },
            { CultistBossLightningOrb, Lightning },
            { CultistBossLightningOrbArc, Lightning },
            { CultistBossFireBall, Fire },
            { CultistBossFireBallClone, Psychic },
            { Nail, Piercing },
            { DrManFlyFlask, Acid },
            { JavelinHostile, Piercing },
            { StardustSoldierLaser, Cold },
            { Twinkle, Cold },
            { StardustJellyfishSmall, Cold },
            { SalamanderSpit, Poison },
            { NebulaBolt, Psychic },
            { NebulaSphere, Psychic },
            { NebulaLaser, Psychic },
            { VortexLaser, Lightning },
            { VortexVortexLightning, Lightning },
            { VortexVortexPortal, Lightning },
            { VortexLightning, Lightning },
            { VortexAcid, Acid },
            { MartianWalkerLaser, Lightning },
            { AncientDoomProjectile, Psychic },
            { DesertDjinnCurse, Fire },
            { TowerDamageBolt, Lightning },
            { SandnadoHostile, Thunder },
            { DD2OgreStomp, Bludgeoning },
            { DD2DrakinShot, Fire },
            { DD2GoblinBomb, Force },
            { DD2LightningBugZap, Lightning },
            { DD2OgreSmash, Bludgeoning },
            { DD2JavelinHostileT3, Piercing },
            { DD2BetsyFireball, Fire },
            { DD2BetsyFlameBreath, Fire },
            { BloodShot, Psychic },
            { BloodNautilusTears, Psychic },
            { BloodNautilusShot, Psychic },
            { HallowBossLastingRainbow, Radiant },
            { HallowBossRainbowStreak, Radiant },
            { HallowBossDeathAurora, Radiant },
            { RockGolemRock, Bludgeoning },
            { QueenSlimeMinionBlueSpike, Piercing },
            { QueenSlimeMinionPinkBall, Acid },
            { QueenSlimeSmash, Force },
            { FairyQueenSunDance, Radiant },
            { QueenSlimeGelAttack, Acid },
            { HorsemanPumpkin, Fire },
            #endregion
            #endregion

            #region Neutral
            { Bomb, Force },
            { StickyBomb, Force },
            { Dynamite, Force },
            { StickyDynamite, Force },
            { BouncyBomb, Force },
            { BouncyDynamite, Force },
            { ScarabBomb, Force },
            { BombFish, Force },
            { ExplosiveBunny, Force },

            { SandBallFalling, Bludgeoning },
            { MudBall, Bludgeoning },
            { AshBallFalling, Bludgeoning },
            { EbonsandBallFalling, Necrotic },
            { CrimsandBallFalling, Psychic },
            { PearlSandBallFalling, Radiant },
            { SiltBall, Bludgeoning },
            { SlushBall, Cold },
            { ShellPileFalling, Piercing },

            { Boulder, Bludgeoning },
            { MiniBoulder, Bludgeoning },
            { BouncyBoulder, Bludgeoning },
            { LifeCrystalBoulder, Bludgeoning },
            { MoonBoulder, Radiant },

            { Explosives, Force },
            { Landmine, Force },
            { PoisonDart, Poison },
            { SpikyBallTrap, Piercing },
            { SpearTrap, Piercing },
            { FlamethrowerTrap, Fire },
            { FlamesTrap, Fire },
            { GeyserTrap, Fire },
            { VenomDartTrap, Poison },
            { TNTBarrel, Force },
            { GasTrap, Poison },
            { CannonballFriendly, Bludgeoning },
            #endregion

            #region Town NPC
            { MechanicWrench, Bludgeoning },
            { NurseSyringeHurt, Poison },
            { ClothiersCurse, Necrotic },
            { SantaBombs, Force },
            { TruffleSpore, Psychic },
            { ZoologistStrikeGreen, Slashing },
            { ZoologistStrikeRed, Force },
            #endregion
        };

        public Element damageTypes;

        public override bool InstancePerEntity => true;

        public override void OnSpawn(Projectile projectile, IEntitySource source)
        {
            if (DefaultDamageTypes.TryGetValue(projectile.type, out var value)) damageTypes |= value;
        }
    }
}
